#!/usr/bin/perl -w
# getbookinfo
# Gets info for a book title and author from local libraries:
#  A) Oregon Library for the Blind (AKA TBABS)
#  B) Multnomah County Library
# Info returned is availability, description and length.

use strict;
#use LWP::Debug qw(+);
use WWW::Mechanize;
#use HTML::TokeParser;
#use HTML::Parser;


my $infile = "./fodder";
my $if;
my $outfile = "./output";

my $tbabsurl = "https://talkingbooks.osl.state.or.us/";

my $mech = WWW::Mechanize->new( autocheck => 1 );
$mech->ssl_opts(  # Don't know why I need this, but I can't connect otherwise
    'SSL_version' => 'TLSv1_2',
    'SSL_cipher_list' => 'ECDHE-RSA-AES256-GCM-SHA384',
    );

open($if, $infile) or die "Couldn't open $infile\n";
while (<$if>) {
    print "\n";
    print $_;

    $mech->get( $tbabsurl );
    $mech->form_number(1);
    $mech->field( "f", "Digital Book" );  # Exclude braille format
    $mech->field( "q", $_ );              # Search on title and author
    $mech->click();
    #print $mech->content;

    # Find first link to title
    $mech->follow_link( url_regex => qr|/title/summary.jsf|i );

    # Extract title
    $mech->content =~ /<td class="Value Field-Title">(.*)</; 
    print "$1\n";
    
    # author
    $mech->content =~ /<td class="Value Field-Names"><a.*>(.*)</; 
    print "$1\n";
    
    # description (AKA Annotation)
    $mech->content =~ /<td class="Value Field-Annotation">(.*)</; 
    print "$1\n";
    
    # length
    $mech->content =~ /<td class="Value Field-Length">(.*)</;
    print "$1\n";

}
close($if);
