#!/bin/bash

if [[ $# -ne 1 ]] || [[ ! "$1" =~ [0-9]+x[0-9]+ ]]; then
    echo "populateTiles <geometry>"
    exit;
fi
geom=$1

for infile in daily-numbers/*gif
do
    number=$( basename -s .gif $infile )
    outfileorig=./$geom/orig/$number.png
    outfileneg=./$geom/negate/$number.png
    if [ ! -f "$outfileorig" ]; then
	convert $infile -resize $geom $outfileorig
    fi
    if [ ! -f "$outfileneg" ]; then
        convert $infile -resize $geom -negate $outfileneg
    fi

    #mean=$( printf "%.0f" $( identify -format "%[mean]" $outfileorig ) );
    #rgb=$( convert $outfileorig -format '#%[hex:u]' info:- )
    hsl=$( convert $outfileorig -scale 1x1 -colorspace HSL -depth 16 txt:- | grep -o "hsl(.*" | tr [:punct:] ' ' )
    echo $hsl orig/$number.png >> ./means

done
