#!/bin/bash
# Read the mean color of each requested image and add it to a file.
# This file is meant to be sorted and then used to find images with the
# correct color values for assembling a montage.

outfile="means"

lines=()
mapfile -t lines < $outfile

for infile in "$@"; do

    if [[ ${lines[@]} =~ $infile ]] ; then
	echo "$infile already calibrated";
    else
	mean=$( printf "%.0f" $( identify -format "%[mean]" $infile ) );
	lines+=("$mean $infile");
    fi

done

printf "%s\n" "${lines[@]}" > $outfile

